#!/usr/bin/python3

import requests
import signal
import sys

signal.signal( signal.SIGINT, lambda signal, frame : exit(255) )

url = sys.argv[1]

response = None
try:
	response = requests.get( url, allow_redirects=False )
except requests.exceptions.MissingSchema:
	print( 'Invalid url: %s' %(url) )
	exit( 2 )

headers = response.headers
if 'Location' in headers:
	print( headers['Location'] )
	exit( 0 )
else:
	exit( 1 )
