#!/usr/bin/perl
use v5.10.1;

$SIG{'INT'} = sub { exit 255 };

use Mojolicious 7;
use Mojo::UserAgent;

my $ua = Mojo::UserAgent->new->max_redirects(0);

my $tx = $ua->get( $ARGV[0] );

eval { $tx->result->is_error; 1 } or exit 2;

if( my $location = $tx->result->headers->location ) {
	say $location;
	exit 0;
	};

exit 1;
