#!/usr/bin/perl
use v5.10.1;

use Mojolicious 7;
use Mojo::UserAgent;
my $ua = Mojo::UserAgent->new;

my $tx = $ua->get( $ARGV[0] );
exit 2 if $tx->result->is_error;

my $location = $tx->result->headers->location;
if( length $location ) {
	say $location;
	exit 0;
	};

exit 1;
