#!/usr/bin/perl
use v5.10.1;

$SIG{'INT'} = sub { exit 255 };

use Mojolicious 7;
use Mojo::UserAgent;

my $ua = Mojo::UserAgent->new->max_redirects(0);

my $url = $ARGV[0];

while( 1 ) {
	my $tx = $ua->get( $url );

	eval { $tx->result->is_error; 1 } or exit 2;

	if( my $location = $tx->result->headers->location ) {
		say $url = $location;
		}
	else {
		exit 0
		}
	}
